language: java
sudo: false
jdk:
- oraclejdk9
- oraclejdk8
- openjdk9
- openjdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  file_glob: true
  file: "target/sassy-scheduler-*.jar"
  skip_cleanup: true
  on:
    tags: true
